trigger: none

variables:
  solution: '**/Hazard.sln'
  buildConfiguration: 'Release'
  storageAccount: 'jm84storage'
  containerName: 'hazard'
  blobPath: '.'

jobs:
  - job: BuildAndPublish
    displayName: 'Build and Publish MSIX'
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        x64:
          buildPlatform: 'x64'
          runtimeId: 'win-x64'
          publishPath: '$(Build.ArtifactStagingDirectory)/publish/x64/'
          msixOutputPath: '$(Build.ArtifactStagingDirectory)/msix/x64/'
          archPath: 'x64'
        ARM64:
          buildPlatform: 'ARM64'
          runtimeId: 'win-arm64'
          publishPath: '$(Build.ArtifactStagingDirectory)/publish/arm64/'
          msixOutputPath: '$(Build.ArtifactStagingDirectory)/msix/arm64/'
          archPath: 'arm64'
    
    steps:
    # Set up .NET SDK
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        includePreviewVersions: false

    # Install wasm-tools workload - this mysteriously helps with runtime packs
    - task: DotNetCoreCLI@2
      displayName: 'Install wasm-tools Workload'
      inputs:
        command: 'custom'
        custom: 'workload'
        arguments: 'install wasm-tools'
        
    # Global restore with runtime identifier
    - task: PowerShell@2
      displayName: 'Global Runtime Pack Restore ($(buildPlatform))'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Performing global restore with runtime identifier $(runtimeId)..."
          # Find solution files and restore them with runtime
          Get-ChildItem -Path "$(Build.SourcesDirectory)" -Filter "*.sln" -Recurse | ForEach-Object {
            Write-Host "Restoring solution: $($_.FullName)"
            dotnet restore "$($_.FullName)" --runtime $(runtimeId) -v normal
          }
    
    # NuGet installation and restore
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages ($(buildPlatform))'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'

    # Standard restore
    - task: DotNetCoreCLI@2
      displayName: 'Restore Solution ($(buildPlatform))'
      inputs:
        command: 'restore'
        projects: '$(solution)'
        arguments: '--runtime $(runtimeId)'

    # Build with explicit framework references and dependencies
    - task: VSBuild@1
      displayName: 'Build Self-Contained MSIX ($(buildPlatform))'
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:RuntimeIdentifier=$(runtimeId) /p:AppxPackageDir=$(msixOutputPath) /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundlePlatforms=$(buildPlatform) /p:AppxBundle=Always /p:GenerateAppInstallerFile=False /p:AppxPackageSigningEnabled=False /p:SelfContained=true /p:WindowsAppSDKSelfContained=true /p:AppxAutoIncrementPackageRevision=True /p:GenerateTestArtifacts=True /p:AppxPackageTestDir=$(msixOutputPath) /p:AppxPackageFileName=HazardGame_$(buildPlatform)'

    - task: CopyFiles@2
      displayName: 'Copy MSIX bundle to publish directory ($(buildPlatform))'
      inputs:
        SourceFolder: '$(msixOutputPath)'
        Contents: |
          **/*.msixbundle
          **/*.appinstaller
        TargetFolder: '$(publishPath)'
        CleanTargetFolder: true
        OverWrite: true

    # Azure CLI setup
    - task: AzureCLI@2
      displayName: 'Azure CLI Setup ($(buildPlatform))'
      inputs:
        azureSubscription: 'JoshMcKnight Azure TopLevel'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$servicePrincipalId" 
          echo "##vso[task.setvariable variable=ARM_ID_TOKEN;issecret=true]$idToken"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$tenantId"
        addSpnToEnvironment: true

    # Azure login
    - bash: |
        az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)
      displayName: 'Azure Login ($(buildPlatform))'

    # Sign the package
    - task: TrustedSigning@0
      displayName: 'Sign with Trusted Signing ($(buildPlatform))'
      inputs:
        Endpoint: 'https://eus.codesigning.azure.net/'
        TrustedSigningAccountName: 'joshmcknightsigning'
        CertificateProfileName: 'JoshuaMcKnight'
        FilesFolder: '$(publishPath)'
        FilesFolderRecurse: true
        FilesFolderFilter: '*.msixbundle'
        ExcludeEnvironmentCredential: true
        ExcludeWorkloadIdentityCredential: true
        ExcludeManagedIdentityCredential: true
        ExcludeSharedTokenCacheCredential: true
        ExcludeVisualStudioCredential: true
        ExcludeVisualStudioCodeCredential: true
        ExcludeAzureCliCredential: false
        ExcludeAzurePowershellCredential: true
        ExcludeAzureDeveloperCliCredential: true
        ExcludeInteractiveBrowserCredential: true

    - task: AzureCLI@2
      displayName: 'Copy to Blob Storage and Set Content Types ($(buildPlatform))'
      inputs:
        azureSubscription: 'JoshMcKnight Azure TopLevel'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Define blob destination path with architecture
          $archSpecificPath = "$(blobPath)/$(archPath)"
          
          # Upload using the service principal auth with overwrite
          az storage blob upload-batch `
            --source "$(publishPath)" `
            --destination "$(containerName)" `
            --destination-path "$archSpecificPath" `
            --account-name "$(storageAccount)" `
            --auth-mode login `
            --overwrite $true
            
          # Get uploaded files to verify names
          $uploadedFiles = az storage blob list --container-name "$(containerName)" --prefix "$archSpecificPath" --account-name "$(storageAccount)" --auth-mode login --query "[].name" -o tsv
          Write-Host "Uploaded files for $(buildPlatform):"
          $uploadedFiles | ForEach-Object { Write-Host "  $_" }
          
          # Find the msix/msixbundle file
          $msixFile = $uploadedFiles | Where-Object { $_ -like "*.msix*" } | Select-Object -First 1
          
          if ($msixFile) {
            Write-Host "Setting content type for: $msixFile"
            # Set content type for MSIX package
            az storage blob update `
              --container-name "$(containerName)" `
              --name "$msixFile" `
              --content-type "application/vnd.ms-appx" `
              --account-name "$(storageAccount)" `
              --auth-mode login
          } else {
            Write-Host "##vso[task.logissue type=warning]No MSIX files found to update content type"
          }