# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release_SelfContained'
  publishPath: '$(Build.ArtifactStagingDirectory)\publish'
  storageAccount: 'jm84storage'
  containerName: 'hazard'
  blobPath: 'self-contained'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: false

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    arguments: '--runtime win-x64'
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:restore;publish 
      /p:PublishProfile=ClickOnce_SelfContained 
      /p:Configuration=Release_SelfContained 
      /p:PublishDir="$(publishPath)" 
      /p:RuntimeIdentifier=win-x64 
      /p:PublishProtocol=ClickOnce 
      /p:GenerateManifests=true'

- task: AzureCLI@2
  displayName: 'Azure Authentication'
  inputs:
    azureSubscription: 'JoshMcKnight Azure TopLevel'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    addSpnToEnvironment: true
    inlineScript: |
      # Explicit login
      az login --service-principal -u "$servicePrincipalId" -t "$tenantId"
      
      # Set subscription
      az account set --subscription "e60fbeed-a1d7-4d83-828e-59d421eae26d"
      
      # Verify login state
      az account show

- task: TrustedSigning@0
  displayName: 'Sign ClickOnce Package'
  inputs:
    Endpoint: 'https://eus.codesigning.azure.net/'
    TrustedSigningAccountName: 'joshmcknightsigning'
    CertificateProfileName: 'JoshuaMcKnight'
    FilesFolder: '$(publishPath)'
    FilesFolderFilter: 'application,exe'
    TimestampRfc3161: 'http://timestamp.acs.microsoft.com'
    TimestampDigest: 'SHA256'
    # Focus on Azure CLI authentication
    ExcludeEnvironmentCredential: true
    ExcludeWorkloadIdentityCredential: true
    ExcludeManagedIdentityCredential: true
    ExcludeSharedTokenCacheCredential: true
    ExcludeVisualStudioCredential: true
    ExcludeVisualStudioCodeCredential: true
    ExcludeAzureCliCredential: false
    ExcludeAzurePowershellCredential: true
    ExcludeAzureDeveloperCliCredential: true
    ExcludeInteractiveBrowserCredential: true
