# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AzureCLI@2
  inputs: 
   azureSubscription: 'JoshMcKnight Azure TopLevel'
   scriptType: 'bash'
   scriptLocation: 'inlineScript'
   inlineScript: |
      # List all role assignments specifically for the Trusted Signing account
      az role assignment list \
        --scope "/subscriptions/e60fbeed-a1d7-4d83-828e-59d421eae26d/resourceGroups/Admin/providers/Microsoft.CodeSigning/codesigningaccounts/joshmcknightsigning" \
        --include-inherited

      # And also try to list assignments specifically for our service principal
      echo "Checking specific service principal assignments:"
      az role assignment list \
        --assignee "298d2c06-f601-45a1-97d3-5dc20cd58fe4" \
        --include-inherited
- task: TrustedSigning@0
  
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
