trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release_SelfContained'
  publishPath: '$(Build.ArtifactStagingDirectory)\publish'
  storageAccount: 'jm84storage'
  containerName: 'hazard'
  blobPath: 'self-contained'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: false

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    arguments: '--runtime win-x64'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:restore;publish
      /p:PublishProfile=ClickOnce_SelfContained
      /p:Configuration=Release_SelfContained
      /p:PublishDir="$(publishPath)"
      /p:RuntimeIdentifier=win-x64
      /p:PublishProtocol=ClickOnce
      /p:GenerateManifests=true'

- task: AzureCLI@2
  displayName: 'Azure CLI'
  inputs:
    azureSubscription: 'JoshMcKnight Azure TopLevel'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$servicePrincipalId"
      echo "##vso[task.setvariable variable=ARM_ID_TOKEN;issecret=true]$idToken"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$tenantId"
    addSpnToEnvironment: true

- bash: |
    az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)
  displayName: 'Azure Login'

- task: TrustedSigning@0
  displayName: 'Sign with Trusted Signing'
  inputs:
    Endpoint: 'https://eus.codesigning.azure.net/'
    TrustedSigningAccountName: 'joshmcknightsigning'
    CertificateProfileName: 'JoshuaMcKnight'
    FilesFolder: '$(publishPath)'
    FilesFolderFilter: 'application,exe'
    ExcludeEnvironmentCredential: true
    ExcludeWorkloadIdentityCredential: true
    ExcludeManagedIdentityCredential: true
    ExcludeSharedTokenCacheCredential: true
    ExcludeVisualStudioCredential: true
    ExcludeVisualStudioCodeCredential: true
    ExcludeAzureCliCredential: false
    ExcludeAzurePowershellCredential: true
    ExcludeAzureDeveloperCliCredential: true
    ExcludeInteractiveBrowserCredential: true

# New storage copy task that uses the existing authentication
- bash: |
    # Get access token for storage
    ACCESS_TOKEN=$(az account get-access-token --resource https://storage.azure.com/ --query accessToken --output tsv)
    
    # Set up AzCopy with explicit credentials
    export AZCOPY_AUTO_LOGIN_TYPE=SPN
    export AZCOPY_SPA_CLIENT_ID="$(ARM_CLIENT_ID)"
    export AZCOPY_SPA_CLIENT_SECRET="$ACCESS_TOKEN"
    export AZCOPY_TENANT_ID="$(ARM_TENANT_ID)"
    
    # Perform the copy
    azcopy cp "$(publishPath)" "https://$(storageAccount).blob.core.windows.net/$(containerName)/$(blobPath)" --recursive
  displayName: 'Copy to Blob Storage'