# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AzureCLI@2
  inputs: 
   azureSubscription: 'JoshMcKnight Azure TopLevel'
   scriptType: 'bash'
   scriptLocation: 'inlineScript'
   inlineScript: |
      # Your Azure CLI commands here
      az account show
      az group list
      az account set --subscription "e60fbeed-a1d7-4d83-828e-59d421eae26d"
      # Then check role assignments
      az role assignment list \
        --assignee "fa0c17c5-68f8-4c08-af95-810ad70c8465" \
        --scope "/subscriptions/e60fbeed-a1d7-4d83-828e-59d421eae26d/resourceGroups/Admin/providers/Microsoft.CodeSigning/codesigningaccounts/joshmcknightsigning"

- task: TrustedSigning@0
  
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
