# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AzureCLI@2
  inputs: 
   azureSubscription: 'JoshMcKnight Azure TopLevel'
   scriptType: 'bash'
   scriptLocation: 'inlineScript'
   inlineScript: |
      # Set subscription explicitly
      az account set --subscription "e60fbeed-a1d7-4d83-828e-59d421eae26d"
      
      # First check roles at resource group level
      echo "Checking roles at resource group level:"
      az role assignment list --resource-group "Admin"
      
      # Then try to get the Trusted Signing account details
      echo "Checking Trusted Signing account details:"
      az resource show \
        --resource-group "Admin" \
        --name "joshmcknightsigning" \
        --resource-type "microsoft.codesigning/codesigningaccounts"
- task: TrustedSigning@0
  
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
