# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release_FrameworkDependent'
  publishPath: '$(Build.ArtifactStagingDirectory)\publish'
  storageAccount: 'jm84storage'
  containerName: 'hazard'
  blobPath: 'framework-dependent'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: false

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:restore;publish /p:PublishProfile=ClickOnce_FrameworkDependent /p:Configuration=Release_FrameworkDependent /p:PublishDir="$(publishPath)" /p:PublishProtocol=ClickOnce /p:GenerateManifests=true /p:RuntimeIdentifier=win-x64 /p:PublishReadyToRun=true'

- task: AzureCLI@2
  displayName: 'Azure CLI'
  inputs:
    azureSubscription: 'JoshMcKnight Azure TopLevel'  # Replace with your connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$servicePrincipalId" 
      echo "##vso[task.setvariable variable=ARM_ID_TOKEN;issecret=true]$idToken"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$tenantId"
    addSpnToEnvironment: true

- bash: |
    az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)
  displayName: 'Azure Login'

- task: TrustedSigning@0
  displayName: 'Sign with Trusted Signing'
  inputs:
    Endpoint: 'https://eus.codesigning.azure.net/'
    TrustedSigningAccountName: 'joshmcknightsigning'
    CertificateProfileName: 'JoshuaMcKnight'
    FilesFolder: '$(publishPath)'
    FilesFolderFilter: 'application,exe'
    ExcludeEnvironmentCredential: true
    ExcludeWorkloadIdentityCredential: true
    ExcludeManagedIdentityCredential: true
    ExcludeSharedTokenCacheCredential: true
    ExcludeVisualStudioCredential: true
    ExcludeVisualStudioCodeCredential: true
    ExcludeAzureCliCredential: false
    ExcludeAzurePowershellCredential: true
    ExcludeAzureDeveloperCliCredential: true
    ExcludeInteractiveBrowserCredential: true

- task: AzureCLI@2
  displayName: 'Copy to Blob Storage and Set Content Types'
  inputs:
    azureSubscription: 'JoshMcKnight Azure TopLevel'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Upload using the service principal auth
      az storage blob upload-batch `
        --source "$(publishPath)" `
        --destination "$(containerName)" `
        --destination-path "$(blobPath)" `
        --account-name "$(storageAccount)" `
        --auth-mode login
      # Set content types for different file extensions
      az storage blob update --container-name "$(containerName)" --name "$(blobPath)/*.application" --content-type "application/x-ms-application" --account-name "$(storageAccount)" --auth-mode login --overwrite
      az storage blob update --container-name "$(containerName)" --name "$(blobPath)/*.manifest" --content-type "application/x-ms-manifest" --account-name "$(storageAccount)" --auth-mode login --overwrite
      az storage blob update --container-name "$(containerName)" --name "$(blobPath)/*.deploy" --content-type "application/octet-stream" --account-name "$(storageAccount)" --auth-mode login --overwrite
      az storage blob update --container-name "$(containerName)" --name "$(blobPath)/*.dll.deploy" --content-type "application/x-msdownload" --account-name "$(storageAccount)" --auth-mode login --overwrite
      az storage blob update --container-name "$(containerName)" --name "$(blobPath)/*.exe.deploy" --content-type "application/x-msdownload" --account-name "$(storageAccount)" --auth-mode login --overwrite
