# Simplified .NET Desktop MSIX packaging pipeline
trigger: none

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  storageAccount: 'jm84storage'
  containerName: 'hazard'

stages:
- stage: FrameworkDependent
  displayName: 'Framework-Dependent Build'
  variables:
    publishPath: '$(Build.ArtifactStagingDirectory)\publish\framework-dependent'
    msixOutputPath: '$(Build.ArtifactStagingDirectory)\msix\framework-dependent'
    blobPath: 'framework-dependent'
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    # Set up .NET SDK
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        includePreviewVersions: false

    # Install wasm-tools workload - this mysteriously helps with runtime packs
    - task: DotNetCoreCLI@2
      displayName: 'Install wasm-tools Workload'
      inputs:
        command: 'custom'
        custom: 'workload'
        arguments: 'install wasm-tools'
        
    # Global restore with runtime identifier - better approach than direct package installation
    - task: PowerShell@2
      displayName: 'Global Runtime Pack Restore'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Performing global restore with runtime identifier..."
          # Find solution files and restore them with runtime
          Get-ChildItem -Path "$(Build.SourcesDirectory)" -Filter "*.sln" -Recurse | ForEach-Object {
            Write-Host "Restoring solution: $($_.FullName)"
            dotnet restore "$($_.FullName)" --runtime win-x64 -v normal
          }


    # NuGet installation and restore
    - task: NuGetToolInstaller@1
      displayName: Install NuGet

    - task: NuGetCommand@2
      displayName: Restore NuGet Packages
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'

    # Standard restore
    - task: DotNetCoreCLI@2
      displayName: 'Restore Solution'
      inputs:
        command: 'restore'
        projects: '$(solution)'
        arguments: '--runtime win-x64'

    # Build with explicit runtime identifier in msbuild args
    - task: VSBuild@1
      displayName: 'Build Framework-Dependent MSIX'
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:RuntimeIdentifier=win-x64 /p:AppxPackageDir="$(msixOutputPath)\\" /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxBundle=Always /p:GenerateAppInstaller=True /p:AppxPackageSigningEnabled=False /p:SelfContained=false'

    # Copy MSIX to publish directory
    - task: CopyFiles@2
      displayName: 'Copy MSIX package to publish directory'
      inputs:
        SourceFolder: '$(msixOutputPath)'
        Contents: '**/*.msix*'
        TargetFolder: '$(publishPath)'
        CleanTargetFolder: false
        OverWrite: true

    # Azure CLI setup
    - task: AzureCLI@2
      displayName: 'Azure CLI'
      inputs:
        azureSubscription: 'JoshMcKnight Azure TopLevel'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$servicePrincipalId" 
          echo "##vso[task.setvariable variable=ARM_ID_TOKEN;issecret=true]$idToken"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$tenantId"
        addSpnToEnvironment: true

    # Azure login
    - bash: |
        az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)
      displayName: 'Azure Login'

    # Sign the package
    - task: TrustedSigning@0
      displayName: 'Sign with Trusted Signing'
      inputs:
        Endpoint: 'https://eus.codesigning.azure.net/'
        TrustedSigningAccountName: 'joshmcknightsigning'
        CertificateProfileName: 'JoshuaMcKnight'
        FilesFolder: '$(publishPath)'
        FilesFolderRecurse: true
        ExcludeEnvironmentCredential: true
        ExcludeWorkloadIdentityCredential: true
        ExcludeManagedIdentityCredential: true
        ExcludeSharedTokenCacheCredential: true
        ExcludeVisualStudioCredential: true
        ExcludeVisualStudioCodeCredential: true
        ExcludeAzureCliCredential: false
        ExcludeAzurePowershellCredential: true
        ExcludeAzureDeveloperCliCredential: true
        ExcludeInteractiveBrowserCredential: true

    # Upload to blob storage# Upload to blob storage
    - task: AzureCLI@2
      displayName: 'Copy to Blob Storage and Set Content Types'
      inputs:
        azureSubscription: 'JoshMcKnight Azure TopLevel'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Upload using the service principal auth with overwrite
          az storage blob upload-batch `
            --source "$(publishPath)" `
            --destination "$(containerName)" `
            --destination-path "$(blobPath)" `
            --account-name "$(storageAccount)" `
            --auth-mode login `
            --overwrite $true

          # Get uploaded files to verify names
          $uploadedFiles = az storage blob list --container-name "$(containerName)" --prefix "$(blobPath)" --account-name "$(storageAccount)" --auth-mode login --query "[].name" -o tsv
          Write-Host "Uploaded files:"
          $uploadedFiles | ForEach-Object { Write-Host "  $_" }
          
          # Find the msix/msixbundle file
          $msixFile = $uploadedFiles | Where-Object { $_ -like "*.msix*" } | Select-Object -First 1
          
          if ($msixFile) {
            Write-Host "Setting content type for: $msixFile"
            # Set content type for MSIX package
            az storage blob update `
              --container-name "$(containerName)" `
              --name "$msixFile" `
              --content-type "application/vnd.ms-appx" `
              --account-name "$(storageAccount)" `
              --auth-mode login
          } else {
            Write-Host "##vso[task.logissue type=warning]No MSIX files found to update content type"
          }

# Self-Contained Build and Deployment
- stage: SelfContained
  displayName: 'Self-Contained Build'
  variables:
    publishPath: '$(Build.ArtifactStagingDirectory)\publish\self-contained'
    msixOutputPath: '$(Build.ArtifactStagingDirectory)\msix\self-contained'
    blobPath: 'self-contained'
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        includePreviewVersions: false

# Nuget Restore needed to properly handle Windows Runtime (for whatever reason)
    - task: NuGetToolInstaller@1
      displayName: Install NuGet

    - task: NuGetCommand@2
      displayName: Restore NuGet Packages
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln' # Replace with the path to your solution file
        arguments: '-RuntimeIdentifier win-x64' # Add the runtime identifier argument
    # Standard restore command
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(solution)'
        feedsToUse: 'select'
        arguments: '--runtime win-x64'

    - task: Cache@2
      displayName: 'Cache NuGet packages'
      inputs:
        key: 'nuget | "$(Agent.OS)" | **/*.csproj'
        restoreKeys: |
          nuget | "$(Agent.OS)"
        path: $(Pipeline.Workspace)/.nuget/packages
        cacheHitVar: 'CACHE_RESTORED'

    - task: VSBuild@1
      displayName: 'Build Self-Contained MSIX'
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:AppxPackageDir="$(msixOutputPath)\\" /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxBundle=Always /p:GenerateAppInstaller=True /p:AppxPackageSigningEnabled=False /p:SelfContained=true'

    - task: CopyFiles@2
      displayName: 'Copy MSIX package to publish directory'
      inputs:
        SourceFolder: '$(msixOutputPath)'
        Contents: '**/*.msix*'
        TargetFolder: '$(publishPath)'
        CleanTargetFolder: false
        OverWrite: true

    - task: AzureCLI@2
      displayName: 'Azure CLI'
      inputs:
        azureSubscription: 'JoshMcKnight Azure TopLevel'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$servicePrincipalId" 
          echo "##vso[task.setvariable variable=ARM_ID_TOKEN;issecret=true]$idToken"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$tenantId"
        addSpnToEnvironment: true

    - bash: |
        az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)
      displayName: 'Azure Login'
    - task: TrustedSigning@0
      displayName: 'Sign with Trusted Signing'
      inputs:
        Endpoint: 'https://eus.codesigning.azure.net/'
        TrustedSigningAccountName: 'joshmcknightsigning'
        CertificateProfileName: 'JoshuaMcKnight'
        FilesFolder: '$(publishPath)'
        ExcludeEnvironmentCredential: true
        ExcludeWorkloadIdentityCredential: true
        ExcludeManagedIdentityCredential: true
        ExcludeSharedTokenCacheCredential: true
        ExcludeVisualStudioCredential: true
        ExcludeVisualStudioCodeCredential: true
        ExcludeAzureCliCredential: false
        ExcludeAzurePowershellCredential: true
        ExcludeAzureDeveloperCliCredential: true
        ExcludeInteractiveBrowserCredential: true

    - task: AzureCLI@2
      displayName: 'Copy to Blob Storage and Set Content Types'
      inputs:
        azureSubscription: 'JoshMcKnight Azure TopLevel'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Upload using the service principal auth with overwrite
          az storage blob upload-batch `
            --source "$(publishPath)" `
            --destination "$(containerName)" `
            --destination-path "$(blobPath)" `
            --account-name "$(storageAccount)" `
            --auth-mode login `
            --overwrite $true

          # Set content type for MSIX package
          az storage blob update `
            --container-name "$(containerName)" `
            --name "$(blobPath)/Hazard.msix" `
            --content-type "application/vnd.ms-appx" `
            --account-name "$(storageAccount)" `
            --auth-mode login